# -*- coding: utf-8 -*-
"""interactive_tutor_app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19iXZpGaudzjY16U632bGo7jZxhb7qDgu
"""

import streamlit as st
from groq import Groq
from PIL import Image
import pytesseract
# Initialize Groq client
client = Groq(api_key="YOUR_GROQ_API_KEY")
st.title("📘 AI Interactive Study Tutor")
st.write("Upload your notes or image, get simple explanations, quizzes, and re-tests!")
# --- Step 1: Upload Notes or Image ---
uploaded_file = st.file_uploader("📄 Upload your notes or image", type=["txt", "jpg", "png", "jpeg"])
if uploaded_file:
    if uploaded_file.name.endswith(".txt"):
        text = uploaded_file.read().decode("utf-8")
    else:
        image = Image.open(uploaded_file)
        text = pytesseract.image_to_string(image)

    st.subheader("🧾 Extracted Notes:")
    st.write(text)
    # --- Step 2: Simplified Explanation ---
    if st.button("💬 Explain in Simple English"):
        prompt = f"Explain the following notes in simple, friendly conversational English as if teaching a beginner:\n\n{text}"
        response = client.chat.completions.create(
            model="llama-3.1-8b-instant",
            messages=[{"role": "user", "content": prompt}],
            max_tokens=500
        )
        ai_explanation = response.choices[0].message.content
        st.subheader("💬 Simplified Explanation:")
        st.write(ai_explanation)
    # --- Step 3: Generate Quiz ---
    if st.button("📝 Generate Quiz"):
        quiz_prompt = f"""
        Based on the following notes, create a quiz to test understanding.
        Include both multiple-choice and short-answer questions.
        Do NOT include answers.

        Notes:
        {text}
        """
        quiz_response = client.chat.completions.create(
            model="llama-3.1-8b-instant",
            messages=[{"role": "user", "content": quiz_prompt}],
            max_tokens=600
        )
        quiz = quiz_response.choices[0].message.content
        st.subheader("📝 Quiz:")
        st.write(quiz)
    # --- Step 4: Student Answers + Feedback ---
    student_answers = st.text_area("✏️ Type your answers here (you can summarize them):")

    if st.button("✅ Check My Answers"):
        feedback_prompt = f"""
        You are a strict but friendly teacher.
        Compare the student's answers with the correct meaning of the topic below:
        {text}

        For each question:
        - Mark as Correct, Wrong, or Partially Correct.
        - If wrong, give a simple 2-line re-explanation.
        - Do NOT overanalyze.

        Student answers:
        {student_answers}
        """
        feedback_response = client.chat.completions.create(
            model="llama-3.1-8b-instant",
            messages=[{"role": "user", "content": feedback_prompt}],
            max_tokens=600
        )
        feedback = feedback_response.choices[0].message.content
        st.subheader("🧾 Feedback:")
        st.write(feedback)
    # --- Step 5: Re-Test Quiz ---
    if st.button("🔁 Re-Test (Generate New Questions)"):
        retest_prompt = f"""
        Based on the student's mistakes above, create 3 new quiz questions
        focusing on weak areas. Do NOT give answers.
        """
        retest_response = client.chat.completions.create(
            model="llama-3.1-8b-instant",
            messages=[{"role": "user", "content": retest_prompt}],
            max_tokens=500
        )
        st.subheader("🔁 Re-Test Quiz:")
        st.write(retest_response.choices[0].message.content)
    # --- Step 6: Re-Explain Button ---
    if st.button("🔁 Re-Explain Topic"):
        re_explain_prompt = f"""
        Please re-explain the topic below in simpler, more conversational English.
        Make it easier for a beginner to understand, like telling a story.

        Notes:
        {text}
        """
        re_explain_response = client.chat.completions.create(
            model="llama-3.1-8b-instant",
            messages=[{"role": "user", "content": re_explain_prompt}],
            max_tokens=500
        )
        st.subheader("🔁 Re-Explanation:")
        st.write(re_explain_response.choices[0].message.content)